#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/stat.h>
#include <regex.h>
#include <sys/wait.h>
#include <time.h>

// Feel free to change the data structures generated by AI.

#define MAX_SYSCALLS 1024
#define TOP_N 5
extern char **environ;

typedef struct {
    char   name[64];
    double time;
} syscall_stat;

typedef struct {   
    int          count;
    double       total_time;
    syscall_stat stats[MAX_SYSCALLS];
} syscall_stats;

int try_exec(const char* program, char* const argv[], char* const envp[]) 
{
    // if program is absolute path( the start is '/')
    if (program[0] == '/') {
        execve(program, argv, envp);
        return -1;
    }

    execve(program, argv, envp);
    
    char full_path[256];

    //“手工” 模拟了 PATH 环境变量的解析
    snprintf(full_path, sizeof(full_path), "/bin/%s", program);
    execve(full_path, argv, envp);

    snprintf(full_path, sizeof(full_path), "/usr/bin/%s", program);
    execve(full_path, argv, envp);

    snprintf(full_path, sizeof(full_path), "/usr/local/bin/%s", program);
    execve(full_path, argv, envp);

    return -1;
}


int parse_strace_line(char *line, char *syscall_name, double *time) 
{
    // strace输出格式: syscall(args) = result <time>
    // 例如: mmap2(0xb76d1000, 10780, PROT_READ|PROT_WRITE, ...) = 0xb76d1000 <0.000011>   
    //正则解析

    static regex_t regex;
    static int regex_compiled = 0;

    if (!regex_compiled) {
        // 正则表达式模式：
        // ^[0-9]*[ \t]*  : 可选的进程ID和空白
        // ([a-zA-Z_][a-zA-Z0-9_]*) : 系统调用名（捕获组1）
        // \(.*\) : 参数部分
        // [ \t]*=[ \t]*[^<]* : 等号和返回值
        // <([0-9]*\.?[0-9]+)> : 时间（捕获组2）

        const char *pattern = "^[0-9]*[ \t]*([a-zA-Z_][a-zA-Z0-9_]*)\\(.*\\)[ \t]*=[ \t]*[^<]*<([0-9]*\\.?[0-9]+)>";
        int result = regcomp(&regex, pattern, REG_EXTENDED);
        if (result != 0) {
            fprintf(stderr, "Failed to compile regex\n");
            return 0;
        }
        regex_compiled = 1;
    }
        // 开始匹配
    regmatch_t matches[3];   // 整个匹配 + 2个捕获组
    int match_result = regexec(&regex, line, 3, matches, 0);

    if (match_result == 0) {
        // 提取系统调用名（捕获组1）
        int name_len = matches[1].rm_eo - matches[1].rm_so;
        if (name_len >= 64) name_len = 63;
        strncpy(syscall_name, line + matches[1].rm_so, name_len);
        syscall_name[name_len] = '\0';

        // 提取时间（捕获组2）
        int time_len = matches[2].rm_eo - matches[2].rm_so;
        char time_str[32];
        if (time_len >= 32) time_len = 31;
        strncpy(time_str, line + matches[2].rm_so, time_len);
        time_str[time_len] = '\0';
        *time = atof(time_str);
        return 1;
    }
    return 0;
}



void add_syscall(syscall_stats *stats, const char *name, double time) 
{
    // 检查系统调用是否已存在
    for (int i = 0; i < stats->count; i++) {
        if (strcmp(stats->stats[i].name, name) == 0) {
            stats->stats[i].time += time;
            stats->total_time    += time;
            return;
        }
    }

    // 新增系统调用
    if (stats->count < MAX_SYSCALLS) {
        strcpy(stats->stats[stats->count].name, name);
        stats->stats[stats->count].time = time;
        stats->count++;
        stats->total_time += time;
    }
}

// 比较函数，用于排序
int compare_syscalls(const void *a, const void *b) 
{
    const syscall_stat *sa = (const syscall_stat *)a;
    const syscall_stat *sb = (const syscall_stat *)b;
    
    if (sa->time > sb->time) return -1;
    if (sa->time < sb->time) return 1;
    return 0;
}

void print_top_syscalls(syscall_stats *stats, int n) 
{
    if (stats->count == 0) {
        // 输出80个\0字符作为分隔符
        for (int i = 0; i < 80; i++) {
            printf("%c", '\0');
        }
        fflush(stdout);
        return;
    }

    // 复制数组并排序
    syscall_stat temp[MAX_SYSCALLS];
    memcpy(temp, stats->stats, stats->count * sizeof(syscall_stat));
    qsort(temp, stats->count, sizeof(syscall_stat), compare_syscalls);

    //根据给定的最大显示数量 n 和实际统计项总数 stats->count
    // 选择一个合适的显示数量。然后，遍历这些统计项
    // 计算每个统计项在其总时间 stats->total_time 中所占的百分比
    // 将结果以“名称 (百分比%)”的格式打印出来。
    int display_count = (n < stats->count) ? n : stats->count;
    for (int i = 0; i < display_count; i++) {
        int ratio = (stats->total_time > 0) ? 
                    (int)((temp[i].time / stats->total_time) * 100) : 
                    0;
        printf("%s (%d%%)\n", temp[i].name, ratio);
    }

    for (int i = 0; i < 80; i++) {
        printf("%c", '\0');
    }
    fflush(stdout);
}

int main(int argc, char *argv[]) 
{

    // 使用错误的参数
    if (argc < 2) {
        fprintf(stderr, "Usage: %s <command> [args...]\n", argv[0]);
        return 1;
    }

    //Creat pipe: [0] for read, [1] for write
    int pipefd[2];
    if (pipe(pipefd) == -1) {
        perror("pipe failed");
        return 1;
    }

    pid_t strace_pid = fork();
    if (strace_pid == 0) {
        //Run strace
        close(pipefd[0]);
        //strace 默认会把 trace 输出到 stderr
        dup2(pipefd[1], STDERR_FILENO);
        close(pipefd[1]);

        char** strace_args = malloc((argc + 2) * sizeof(char*));
        strace_args[0] = "strace";
        strace_args[1] = "-T";

        for (int i = 1; i < argc; i++) {
            strace_args[i + 1] = argv[i];
        }
        strace_args[argc + 1]  = NULL;

        try_exec("strace", strace_args, environ);

        perror("failed to execute strace");
        free(strace_args);
        strace_args = NULL;

        exit(1);
    } else if (strace_pid > 0) {
        close(pipefd[1]);

        FILE* fp = fdopen(pipefd[0], "r");
        if (fp == NULL) {
            perror("fdopen failed");
            exit(1);
        }

        syscall_stats stats = {0};
        char line[1024];
        char syscall_name[64];
        double time;

        clock_t last_print = clock();
        const clock_t print_interval = CLOCKS_PER_SEC / 10;

        while (fgets(line, sizeof(line), fp) != NULL) {
            if (parse_strace_line(line, syscall_name, &time)) {
                add_syscall(&stats, syscall_name, time);
                
                // 检查是否需要打印统计信息（每秒约10次）
                clock_t current_time = clock();
                if (current_time - last_print >= print_interval) {
                    print_top_syscalls(&stats, TOP_N);
                    last_print = current_time;
                }
            }
        }
        
        fclose(fp);
        print_top_syscalls(&stats, TOP_N);
        // 等待strace进程结束
        int status;
        waitpid(strace_pid, &status, 0);
        
        // 程序退出时，sperf也退出（不需要最终统计）
    } else {
        perror("fork failed");
    }
    
    return 0;
}
